name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v3
      - name: Build & Test
        run: ./gradlew clean test shadowJar --stacktrace
      - name: Upload JAR
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: plugin-jars
          path: build/libs/*-all.jar