name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v3
      - name: Set version from tag
        run: echo "PLUGIN_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      - name: Build release JAR
        run: ./gradlew clean shadowJar -PskipTests --stacktrace
        env:
          PLUGIN_VERSION: ${{ env.PLUGIN_VERSION }}
      - name: Capture artifact name
        id: jar
        run: |
          FILE=$(ls build/libs/*-all.jar | head -n1)
          echo "file=$FILE" >> $GITHUB_OUTPUT
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            ${{ steps.jar.outputs.file }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}